### ISSUE TITLE
Release of training log or tensorboard for FlexMatch on CIFAR100

### ISSUE THREAD

**Issue by HeimingX** [TorchSSL/TorchSSL#13]
Dear authors, 

Thanks for the impressive work FlexMatch and the awesome codebase!

Recently, I am trying to conduct some experiments on CIFAR100 based on this repo and I just found that FlexMatch training may cost around 50min for 5k iterations (3 * NVIDIA RTX2080Ti) which may take 7 days for the whole training. It is quite a long period.

I wonder if it is possible for you to release the training log or tensorboard for FlexMatch method on CIFAR100 to provide me a reference which would help me a lot. Many many thanks~

Cheers,
Haiming

**Comment by 18445864529** [comment]
Hi, Haiming, thank you for your interest! 
The experiments were done with an internal repo and internal machines, so I'm afraid it's difficult to retrieve the log. 
We are currently reproducing the benchmark results under this new repo and will update in the readme soon, so please just wait another couple of days.

Best.

**Comment by wanghao14** [comment]
@18445864529 Hi, can you recall how long it took to train before? This code runs really slowly: It took 9 hours to train 45000 iters on 1 RTX3090.

**Comment by qianlanwyd** [comment]
> @18445864529 Hi, can you recall how long it took to train before? This code runs really slowly: It took 9 hours to train 45000 iters on 1 RTX3090.

Because wrn-28-8 is very big, so the training is very slow. The speed in 3090 is normal.

**Comment by wanghao14** [comment]
Thanks very much for your reply. The demand for this resource is not very friendly to school researchers.

**Comment by qianlanwyd** [comment]
> Thanks very much for your reply. The demand for this resource is not very friendly to school researchers.

Thanks for your understanding. If you use google's repo, it will cause the almost same time for training.

**Comment by wanghao14** [comment]
@qianlanwyd Hi, I tried 8 gpu for training CIFAR-100 but get the error: `OSError: [Errno 12] Cannot allocate memory` and I found that all my 256 Memory ran out during the data loading process. Is it a code design problem？

**Comment by wanghao14** [comment]
The detailed error message:

**Comment by wanghao14** [comment]
The detailed error message:

> flexmatch.py:42: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
flexmatch.py:49: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
[2021-11-27 09:41:50,922 WARNING] USE GPU: 2 for training
[2021-11-27 09:41:50,922 WARNING] USE GPU: 4 for training
[2021-11-27 09:41:50,922 WARNING] USE GPU: 1 for training
[2021-11-27 09:41:50,923 WARNING] USE GPU: 6 for training
[2021-11-27 09:41:50,922 WARNING] USE GPU: 5 for training
[2021-11-27 09:41:50,924 WARNING] USE GPU: 7 for training
[2021-11-27 09:41:50,924 WARNING] USE GPU: 3 for training
[2021-11-27 09:41:50,928 WARNING] USE GPU: 0 for training
[2021-11-27 09:41:51,303 INFO] Number of Trainable Params: 23409092
[2021-11-27 09:41:51,450 INFO] model_arch: <models.flexmatch.flexmatch.FlexMatch object at 0x7fc99aab5990>
[2021-11-27 09:41:51,450 INFO] Arguments: Namespace(T=0.5, alg='flexmatch', amp=False, batch_size=8, bn_momentum=0.0010000000000000009, c='config/flexmatch/flexmatch_cifar100_400_0.yaml', clip=0, data_dir='./data', dataset='cifar100', depth=28, dist_backend='nccl', dist_url='tcp://127.0.0.1:10002', distributed=True, dropout=0.0, ema_m=0.999, epoch=1, eval_batch_size=1024, gpu=0, hard_label=True, leaky_slope=0.1, load_path='None', lr=0.03, momentum=0.9, multiprocessing_distributed=True, net='WideResNet', net_from_name=False, num_classes=100, num_eval_iter=5000, num_labels=400, num_train_iter=1048576, num_workers=16, optim='SGD', overwrite=True, p_cutoff=0.95, rank=0, resume=False, save_dir='./saved_models', save_name='flexmatch_cifar100_400_0', seed=0, thresh_warmup=True, train_sampler='RandomSampler', ulb_loss_ratio=1.0, uratio=7, use_DA=False, use_tensorboard=True, weight_decay=0.001, widen_factor=8, world_size=8)
[2021-11-27 09:41:53,516 INFO] [!] data loader keys: dict_keys(['train_lb', 'train_ulb', 'eval'])
first_stride in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7fc83898d950> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
first_stride in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7f90ca434490> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
first_stride in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7efaae5a9610> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
first_stride in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7fdce96ae050> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
first_stride in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7fb8d8704950> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
first_stride in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7fedaae57410> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
first_stride in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7f35cd43be50> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
first_stride in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: 1 -> 1
depth in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: 28 -> 28
widen_factor in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: 2 -> 8
leaky_slope in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: 0.0 -> 0.1
bn_momentum in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: 0.01 -> 0.0010000000000000009
dropRate in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: 0.0 -> 0.0
use_embed in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: False -> False
is_remix in <models.nets.wrn.build_WideResNet object at 0x7f544437c4d0> is overlapped by kwargs: False -> False
Files already downloaded and verified
Files already downloaded and verified
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fdcf2fb1830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb82b308830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fc8ed6ba830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f917f161830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fee5fb82830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f54f90a8830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7efb632d6830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f367b138830>
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1174, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Traceback (most recent call last):
  File "flexmatch.py", line 351, in <module>
    main(args)
  File "flexmatch.py", line 64, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:
-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data2/zoro/codes/SSL/TorchSSL/flexmatch.py", line 236, in main_worker
    trainer(args, logger=logger)
  File "/data2/zoro/codes/SSL/TorchSSL/models/flexmatch/flexmatch.py", line 129, in train
    self.loader_dict['train_ulb']):
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/data2/zoro/anaconda3/envs/ssl/lib/python3.7/multiprocessing/util.py", line 455, in spawnv_passfds
    False, False, None)
OSError: [Errno 12] Cannot allocate memory

**Comment by qianlanwyd** [comment]
Each gpu will generate their own random indexes for training. Maybe this is the reason.
Currently I am an intern at MSRA, and my workload is very big now.  So please just use 1~4 GPUs for training at this moment. We will re-organize this part in the future.

**Comment by wanghao14** [comment]
OK, just want to report this problem for finding the potential bugs as you had trained this code successfully. I will try different configurations and read the code to understand it better. Wish everything goes well with your work.

**Comment by 18445864529** [comment]
Maybe you can also try reducing your batch size which may fix the problem.

Best.
