### ISSUE TITLE
Run on single GPU

### ISSUE THREAD

**Issue by ramdhan1989** [TorchSSL/TorchSSL#16]
can I run the code using single GPU ?

**Comment by 18445864529** [comment]
Yes, you can. The code will use all your available GPU(s) by default.

**Comment by ramdhan1989** [comment]
I got error like this :
```
Traceback (most recent call last):
  File "flexmatch.py", line 351, in <module>
    main(args)
  File "flexmatch.py", line 66, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "flexmatch.py", line 199, in main_worker
    torch.distributed.barrier()
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\distributed\distributed_c10d.py", line 1946, in barrier
    _check_default_pg()
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\distributed\distributed_c10d.py", line 211, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```
I change multiprocessing_distributed to False and GPU to 0 in config file. any idea ?

thank you

**Comment by 18445864529** [comment]
Could you try directly running the project on your single GPU without
changing the default argument and see if this error still exists?

**Comment by ramdhan1989** [comment]
This is if I change multiprocessing_distributed to True (default)

```
flexmatch.py:42: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
flexmatch.py:49: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Traceback (most recent call last):
  File "flexmatch.py", line 351, in <module>
    main(args)
  File "flexmatch.py", line 64, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\multiprocessing\spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\multiprocessing\spawn.py", line 157, in start_processes
    while not context.join():
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\multiprocessing\spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\multiprocessing\spawn.py", line 19, in _wrap
    fn(i, *args)
  File "D:\Ramdhan\dynocard\TorchSSL-main\flexmatch.py", line 93, in main_worker
    world_size=args.world_size, rank=args.rank)
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\distributed\distributed_c10d.py", line 421, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "C:\Users\Owner\Anaconda3\envs\nlp\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for tcp://
```

**Comment by qianlanwyd** [comment]
I will re-open it if you still have questions
