### ISSUE TITLE
Question about DistributedDataParallel()

### ISSUE THREAD

**Issue by wenqinl** [TorchSSL/TorchSSL#55]
I was trying to run it under the setting of 1node4gpus, it throws this error:
Traceback (most recent call last):
  File "fixmatch.py", line 357, in <module>
    main(args)
  File "fixmatch.py", line 67, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGBUS

The entire environment is exactly the same as provided in the "environment.yaml". Can you please give me some suggestions on this issue? Thank you so much!

**Comment by 18445864529** [comment]
Hi, did this happen before the training even started or during the training? 
If it's the former, make sure the distributed arguments are correctly set (i.e. `word-size`, `rank`, `dist-url`), in your case, the default value should work. And also make sure your `CUDA_VISIBLE_DEVICES=0,1,2,3`. 
For the latter, it may be because of some memory issues, please try reducing  `num_worker` and `batch_size` and see if it solves the problem.

**Comment by Ajaypatel1234** [comment]
Hi, I have a problem training a model using 2 Nodes (each contains 4 GPUs). I have changed world-size = 2, rank = 1 and the dist-url is the same as you mentioned in the config file. Unfortunately, PyTorch only recognises 4 GPUs instead of 8. Could you please tell me what could the root cause? The server is using SLURM to queue a job. Thanks in advance.

**Comment by 18445864529** [comment]
@Ajaypatel1234 According to your description, did you set rank=1 on both machines (nodes)? In your case, you should set rank=0 on the first node and rank=1 on the second.
